name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    env:
      MIX_ENV: test
    strategy:
      matrix:
        include:
          - elixir: 1.13.3
            otp: 24.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/OTP
        uses: erlef/setup-beam@v1.16.0
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-

      - name: Install mix dependencies and compile
        run: mix do deps.get, compile --warnings-as-errors --all-warnings

      - name: Unlock unused dependecies
        run: mix deps.unlock --check-unused

      - name: Check formatting
        run: mix format --check-formatted

      - name: Credo
        run: mix credo --strict

      - name: Restore PLT cache
        id: plt_cache
        uses: actions/cache/restore@v3
        with:
          key: |
            plt-${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            plt-${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-
          path: |
            priv/plts

      # Create PLTs if no cache was found
      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      # By default, the GitHub Cache action will only save the cache if all steps in the job succeed,
      # so we separate the cache restore and save steps in case running dialyzer fails.
      - name: Save PLT cache
        id: plt_cache_save
        uses: actions/cache/save@v3
        if: steps.plt_cache.outputs.cache-hit != 'true'
        with:
          key: |
            plt-${{ runner.os }}-mix-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          path: |
            priv/plts

      - name: Run dialyzer
        run: mix dialyzer --format github

      - name: Run tests
        run: mix coveralls.lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          files: cover/lcov.info
